type Query {
  node(id: String!): Node!
  hello: String!
  user(id: String!): User!
  me: User!
  upvotes(id: String!): Upvote!
  colorPalettesPublic: [ColorPalette!]!
  colorPalette(id: String!): ColorPalette!
}

interface Node {
  id: ID!
}

type User implements Node {
  id: ID!
  displayName: String!
  profilePictureUrl: String!
  roles: [DiscordRole!]!
  createdColorPalettes: [ColorPalette!]!
}

type DiscordRole {
  id: ID!
  displayName: String!
  colorHex: String!
}

type ColorPalette implements Node {
  id: ID!
  name: String!
  colors: [ColorPaletteItem!]!
  isPublic: Boolean!
  author: User!
}

type ColorPaletteItem {
  id: Float!
  name: String!
  r: Float!
  g: Float!
  b: Float!
  a: Float!
  hex: String!
}

type Upvote implements Node {
  id: ID!
  count: Float!
  isUpvotedByMe: Boolean!
}

type Mutation {
  upvotesAdd(id: String!, userId: String!): Upvote!
  upvotesRemove(id: String!, userId: String!): Upvote!
  colorPaletteCreate(input: ColorPaletteCreateInput!): ColorPalette!
  colorPaletteAddColor(input: ColorPaletteItemAddInput!): ColorPalette!
  colorPaletteRemoveColor(input: ColorPaletteItemRemoveInput!): ColorPalette!
  colorPaletteDelete(id: String!): Boolean!
}

input ColorPaletteCreateInput {
  name: String!
  authorUserId: String!
  colors: [ColorPaletteItemInput!]!
  isPublic: Boolean!
}

input ColorPaletteItemInput {
  name: String
  r: Float
  g: Float
  b: Float
  a: Float
  hex: String
}

input ColorPaletteItemAddInput {
  colorPaletteId: String!
  colors: [ColorPaletteItemInput!]!
}

input ColorPaletteItemRemoveInput {
  colorPaletteId: String!
  colorId: Float!
}
