name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Env
        run: |
          touch .env
          echo 'VUE_APP_FIREBASE_CONFIG=${{ secrets.VUE_APP_FIREBASE_CONFIG }}' >> .env
          echo 'VUE_APP_GRAPHQL_ENDPOINT=https://server.gmlounge.games/graphql' >> .env
          echo 'VUE_APP_OAUTH_LOGIN_ENDPOINT=https://server.gmlounge.games/oauth/discord/login' >> .env
          echo 'VUE_APP_SELF_ENDPOINT=https://www.gmlounge.games' >> .env
          echo 'VUE_APP_SOCKET_IO_ENDPOINT=https://server.gmlounge.games' >> .env
          echo 'VUE_APP_VERSION=2.0.3' >> .env
      - name: Build
        run: yarn install && yarn build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GMDISCORD_FE86C }}'
          channelId: live
          projectId: gmdiscord-fe86c
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels